name: Run Tests

on:
  pull_request:
    branches: [ test ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install unittest2  # if needed, else standard unittest works

      - name: Run Unit Tests
        run: |
          python test.py
